<div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 wow fadeInUp" data-wow-delay=".2s">
        <div class="usa_item_list">
          <div class="usa_item_img"><a href="[field:arcurl/]" title="[field:title/]"><img src="[field:picname/]" height="219px" width="370px" /></a></div>
          <div class="usa_item_title"><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></div>
        </div>
      </div>