<?php
$z[0]=Array("arcurl","",100,115);
$z[0][4]=array();
$z[1]=Array("picname","",127,143);
$z[1][4]=array();
$z[2]=Array("arcurl","",248,263);
$z[2][4]=array();
$z[3]=Array("title","",266,280);
$z[3][4]=array();
$z[4]=Array("click","",348,362);
$z[4][4]=array();
$z[5]=Array("pubdate","",385,432);
$z[5][4]=array();
$z[5][4]['function']="MyDate('Y-m-d',@me)";
$z[6]=Array("description","",484,504);
$z[6][4]=array();

?>