<div class="art_list wow fadeInUp">
            <div class="art_img"><a href="[field:arcurl/]" title="[field:title/]"><img src="[field:picname/]" alt="[field:title/]" /></a></div>
            <div class="art_right">
              <div class="art_title"><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></div>
              <div class="art_des">[field:info/]</div>
            </div>
          </div>