<div class="col-lg-4 col-md-6 col-xs-12 pro_item  wow fadeInUp" data-wow-delay=".2s">
        <div class="pro_item_img"><a href="[field:arcurl/]" title="[field:title/]"><img src="[field:picname/]" alt="[field:title/]" height="219px" width="370px"/></a></div>
        <div class="pro_item_title"><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></div>
        <div class="pro_item_more"><a href="[field:arcurl/]" title="[field:title/]">MORE</a></div>
      </div>