<div class="col-lg-2 col-md-4 col-xs-6 home_item_list wow fadeInUp animated" data-wow-delay=".6s" style="visibility: visible; animation-delay: 0.6s; animation-name: fadeInUp;">
        <div class="home_item_img"><a href="[field:typelink/]" title="[field:typename/]"><img src="/skin/images/20161116165630621.png" data-old="/skin/images/20161116165630621.png" data-new="/skin/images/20161118154628651.png"></a></div>
        <div class="home_item_title"><a href="[field:typelink/]" title="[field:typename/]">[field:typename/]</a></div>
        <div class="home_item_des">[field:description/]</div>
      </div>