<?php
$z[0]=Array("global","",87,113);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",164,190);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","(@me==\"\")? @me=\" class='current' \":@me=\"\";",776,868);
$z[2][4]=array();
$z[2][4]['name']="typeid";
$z[2][4]['runphp']="yes";
$z[3]=Array("channelartlist","\r\n          <li><a class='{dede:field.currentstyle/}' href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}</a>\r\n            <ul>\r\n              {dede:channel type='son' noself='yes'}\r\n              <li><a href='[field:typelink/]'>[field:typename/]</a></li>\r\n              {/dede:channel}\r\n            </ul>\r\n          </li>\r\n          ",905,1340);
$z[3][4]=array();
$z[3][4]['typeid']="top";
$z[3][4]['row']="8";
$z[3][4]['currentstyle']="current";
$z[4]=Array("channelartlist","\r\n          <li><a href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}<i class=\"touch-arrow-down\"></i></a>\r\n            <ul>\r\n              {dede:channel type='son' noself='yes'}\r\n              <li><a href='[field:typelink/]'>[field:typename/]</a></li>\r\n              {/dede:channel}\r\n            </ul>\r\n          </li>\r\n          ",1561,1970);
$z[4][4]=array();
$z[4][4]['typeid']="top";
$z[4][4]['row']="8";

?>