<?php
$z[0]=Array("field","",202,221);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",222,248);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",289,311);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",351,403);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1079,1114);
$z[4][4]=array();
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1411,1469);
$z[5][4]=array();
$z[5][4]['name']="typeid";
$z[5][4]['function']="GetTopTypename(@me)";
$z[6]=Array("channel","\r\n              <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n              ",1591,1829);
$z[6][4]=array();
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li><a href='~typelink~' class='current'>~typename~</a></li>";
$z[7]=Array("field","",1972,2001);
$z[7][4]=array();
$z[7][4]['name']="typename";
$z[8]=Array("include","",4525,4562);
$z[8][4]=array();
$z[8][4]['filename']="footer.htm";

?>